<a href="https://colab.research.google.com/github/Priyagane/Numpy_mini_project/blob/main/mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

data_file ='/content/drive/MyDrive/Data_sets/makeSenseOfCensus.csv'

data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)



Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# New Section

In [ ]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [ ]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]

data1 = np.concatenate((data,new_record))
print(data1)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [ ]:
age = data1[:,:1]
#print(age)

In [ ]:
max_age=age.max()
print(max_age)

90.0


In [ ]:
min_age=age.min()
print(min_age)

17.0


In [ ]:
age_mean=age.mean()
print(age_mean)

38.06293706293706


In [ ]:
age_std=age.std()
print(age_std)

13.341478176165857


In [ ]:
race_col = data1[:,2:3]
race_0=(race_col[race_col == 0])
print(race_0)
race_1=(race_col[race_col == 1])
print(race_1)
race_2=(race_col[race_col == 2])
print(race_2)
race_3=(race_col[race_col == 3])
print(race_3)
race_4=(race_col[race_col == 4])
print(race_4)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4

In [ ]:
len_0=len(race_0)
print("race0: ",len_0)
len_1=len(race_1)
print("race1: ",len_1)
len_2=len(race_2)
print("race2: ",len_2)
len_3=len(race_3)
print("race3: ",len_3)
len_4=len(race_4)
print("race4: ",len_4)



race0:  10
race1:  27
race2:  110
race3:  6
race4:  848


In [ ]:
min_no_citizen = np.array([len_0,len_1,len_2,len_3,len_4])
a = min_no_citizen.min()
print(a) 
    
if a==len_0:
  print("race0 with the minimum no. of citizens")
elif a==len_1:
  print("race1 with the minimum no. of citizens")
elif a==len_2:
  print("race2 with the minimum no. of citizens")
elif a==len_3:
  print("race2 with the minimum no. of citizens")
elif a==len_4:
  print("race4 with the minimum no. of citizens")
      




6
race2 with the minimum no. of citizens


In [ ]:
minority_race = np.where(min_no_citizen == min(min_no_citizen))

print(minority_race)
print("Index of the race having the least no. of citizens",minority_race[0])

(array([3]),)
Index of the race having the least no. of citizens [3]


In [ ]:
senior_citizens = age[age>60]
print(senior_citizens)

[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]


In [ ]:
working_hours = data1[:,6]

c = np.extract(age>60,working_hours)
working_hours_sum = sum(c)
print(working_hours_sum)

#c= working_hours[np.where(age>60)[0]]
#print(c.size)
#c = working_hours 
#print(c)

1917.0


In [ ]:
senior_citizens_len = len(senior_citizens)
print(senior_citizens_len)

61


In [ ]:
avg_working_hours = working_hours_sum/senior_citizens_len
print(avg_working_hours)   
if avg_working_hours < 25:
  print(" govt. policy is followed.")
else:
  print(" govt. policy not is followed.")

31.42622950819672
 govt. policy not is followed.


In [ ]:
education = data1[:,1]
high = education[education > 10] 
low = education[education <= 10]
print(high.size)
print(low.size)

327
674


In [ ]:
income = data1[:,7]
pay_high = np.extract(education >10,income)
avg_pay_high = pay_high.mean()
pay_low = np.extract(education <=10,income)
avg_pay_low = pay_low.mean()
print(avg_pay_high)
print(avg_pay_low)


0.42813455657492355
0.13649851632047477


In [ ]:
if avg_pay_high > avg_pay_low:
  print("Higher educated people have better pay in general")
else:
  print("lower educated people have better pay in general")


Higher educated people have better pay in general
