<a href="https://colab.research.google.com/github/Priyagane/Numpy_mini_project/blob/main/num_py_mini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lst = [10,200,90,0]
import numpy as np
arr = np.array(lst)
print(arr +10)

[ 20 210 100  10]


In [ ]:
lst = [10,20,30,40]
import numpy as np
import sys
arr = np.array(lst)
print(arr.nbytes)
print(sys.getsizeof(lst))

32
104


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print("------")
print(b)

[1 2 3 4]
------
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([[1,2,3],[5,6,7],[3,8,3]])

print('The shape of the array a is',a.shape)
print('The shape of the array b is',b.shape)  
print('The dimension of the array a is',a.ndim)
print('The dimension of the array b is',b.ndim)  
print('The size of the array a is ', a.size)
print('The size of the array b is ', b.size)    
print('The datatype of the array a is ', a.dtype)
print('The datatype of the array b is ', b.dtype)  
print(a.nbytes)
print('The number of bytes in each element of the array a is ', a.itemsize)
print('The number of bytes in each element of the array b is ', b.itemsize)

The shape of the array a is (4,)
The shape of the array b is (3, 3)
The dimension of the array a is 1
The dimension of the array b is 2
The size of the array a is  4
The size of the array b is  9
The datatype of the array a is  int64
The datatype of the array b is  int64
32
The number of bytes in each element of the array a is  8
The number of bytes in each element of the array b is  8


In [ ]:
print(np.array([5,6,7,8,9,6,7,8,9]).shape)

(9,)


In [ ]:
print(np.matrix([1,2]).shape)

(1, 2)


In [ ]:
print(np.eye(3))
print(np.zeros( (4,3), dtype = 'int64' ) )
print(np.ones((3,3), dtype= 'float64' ))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(1,20,dtype='int32'))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(np.arange(1,20,2,dtype='int8'))

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
x=np.arange(24).reshape(4,3,2)
print(x)
print(x.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
3


In [ ]:
marks=np.array([20,30,40])
Ids=np.array([0,2,4])
print("Students Marks",marks)
print("Students ID",Ids)

Students Marks [20 30 40]
Students ID [0 2 4]


In [ ]:
import numpy as np
arr1 =np.array([25,56,12,85,34,75])
print(arr1)
arr2 =np.array([42,3,86,32,856,46])
print(arr2)
Narr =np.random.rand(6)               
print(Narr)
arr1=arr1.astype(complex)
print(arr1)

[25 56 12 85 34 75]
[ 42   3  86  32 856  46]
[0.29926164 0.07237863 0.91186555 0.22710015 0.38106109 0.54559832]
[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[2][1])
print("============")
print(a[:2,:3])
print("===========")
print(a[2,:])
print("===========")
print(a[0:3, 0:2])

8
[[1 2 3]
 [4 5 6]]
[7 8 9]
[[1 2]
 [4 5]
 [7 8]]


In [47]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[[0,1,2],[0,1,0]])
print('==========')
print(np.array([a[0,0],a[1,1],a[2,0]]))
print('==========')
print(a[[0,0],[1,1]])
print('==========')

print(np.array([a[0,1],a[0,1]]))


[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [ ]:
a = np.array([[4,7,1],[2,5,7],[7,1,1]])

# Boolean condition for values greater than 3
mask = a > 3
print(mask)

# Masking for the above boolean condition in the array
print(a[mask])

[[ True  True False]
 [False  True  True]
 [ True False False]]
[4 7 5 7 7]


In [ ]:
a = np.array([3,4.5,3+5j,0])
print(np.isreal(a))
print(np.iscomplex(a))


[ True  True False  True]
[False False  True False]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[arr > 2])

[3 4 5 6 7]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [ ]:
a = np.array([[1,4,9],[16,25,36]])
print(np.sqrt(a))

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
import numpy as np
a = np.array([[2,4,17],[8,10,12],[14,16,18]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.log(a))
print(a.sum())
print(a.min())
print(a.min(axis=0))
print(a.cumsum(axis=1))
print(a.mean())
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))

[[12 15 29]
 [21 24 27]
 [30 33 36]]
[[-8 -7  5]
 [-5 -4 -3]
 [-2 -1  0]]
[[ 20  44 204]
 [104 140 180]
 [224 272 324]]
[[0.69314718 1.38629436 2.83321334]
 [2.07944154 2.30258509 2.48490665]
 [2.63905733 2.77258872 2.89037176]]
101
2
[ 2  4 12]
[[ 2  6 23]
 [ 8 18 30]
 [14 30 48]]
11.222222222222221
12.0
[[1.        0.9208637 0.9208637]
 [0.9208637 1.        1.       ]
 [0.9208637 1.        1.       ]]
5.370242654930921


In [ ]:
a = np.array([5,6,7,8])
b = np.array([5,6,7,8])
print(np.array_equal(a,b))

True


In [ ]:
a = np.array([[2,5,7],[4,25,30]])

# computes sum over columns
print(a.sum(axis=1))
print('==========')

# computes sum over rows
print(a.sum(axis=0))
print('==========')

# computes total sum
print(a.sum())

[14 59]
[ 6 30 37]
73


In [ ]:
import numpy as np
#a = np.array([40,35,20,21,48,70]) 
a = np.array([[40,35,20],[21,48,70]]) 

b = a[0].min()

print("minimum price of day one", b)
c = max(a[1])
#c = a.max()
print("minimum price of day one",c)
p =np.subtract(b,c)
print("Total Profit", abs(p))
#day1 ,day2 = list(a)
Ind_min = np.where(a==b)
print("day1 minimum element's index value",Ind_min)
# Ind_max = np.where(a==c)
# print("day1 minimum element's index value",Ind_max)

#list(day1).index(20)

minimum price of day one 20
minimum price of day one 70
Total Profit 50
day1 minimum element's index value (array([0]), array([2]))


In [49]:
x = np.array([[[1, 2, 3], [3, 4, 6]],[[1, 2, 3], [3, 4, 6]],[[1, 2, 3], [3, 4, 6]]])
y = np.array([[5, 6]])
#np.concatenate((x, y),axis=0)
x.shape
print(x)
print("===========")
print(x.shape)
#x.reshape(3,2,2)
#x.sum(axis=2)
print("===========")
print(x.sum(axis=0))
print("===========")
print(x.sum(axis=1))
print("===========")
print(x.sum(axis=2))
print(x.max(axis=0))


[[[1 2 3]
  [3 4 6]]

 [[1 2 3]
  [3 4 6]]

 [[1 2 3]
  [3 4 6]]]
(3, 2, 3)
[[ 3  6  9]
 [ 9 12 18]]
[[4 6 9]
 [4 6 9]
 [4 6 9]]
[[ 6 13]
 [ 6 13]
 [ 6 13]]
[[1 2 3]
 [3 4 6]]


In [ ]:
a = np.arange(36)
b= a.reshape(4,3,3)
print(a)
print(b)
print(b[3,:,1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
[28 31 34]


In [ ]:
import numpy as np
print(np.arange(3) + 4)
print(np.ones((3,3)) + np.arange(3))
print(np.arange(3).reshape((3,1)) + np.arange(3))


[4 5 6]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np
print(np.matrix([1,2,3,4]).shape)

(1, 4)


In [ ]:
a = np.random.random((5,5))
print(a)
a_min=a.min()
a_max=a.max()
z_norm = (a-a_min)/(a_max-a_min)
print(z_norm)
#print(a([0:1]))


[[0.71405416 0.99909072 0.8431182  0.3701571  0.83514957]
 [0.78613923 0.33869733 0.15652088 0.53347748 0.99199522]
 [0.3414388  0.17379424 0.4264915  0.41102829 0.20821619]
 [0.68147827 0.02909029 0.29335282 0.81406357 0.98937718]
 [0.14946865 0.75227849 0.79016647 0.36023969 0.43754888]]
[[0.70614801 1.         0.83920366 0.35161512 0.83098858]
 [0.78046249 0.31918237 0.13137169 0.51998656 0.99268506]
 [0.32200863 0.14917927 0.40969179 0.39375034 0.18466579]
 [0.67256464 0.         0.27243548 0.80925045 0.98998605]
 [0.12410135 0.74555452 0.78461427 0.34139098 0.42109115]]


In [ ]:
import numpy as np 

data_file ='/content/drive/MyDrive/Data_sets/makeSenseOfCensus.csv'

data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)



Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [ ]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [ ]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]

data1 = np.concatenate((data,new_record))
print(data1)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [ ]:
age = data[:,:1]
#print(age)

In [ ]:
max_age=age.max()
print(max_age)

90.0


In [ ]:
min_age=age.min()
print(min_age)

17.0


In [ ]:
age_mean=age.mean()
print(age_mean)

38.051


In [ ]:
age_std=age.std()
print(age_std)

13.342803266180612


In [ ]:
race_col = data[:,2:3]
race_0=(race_col[race_col == 0])
print(race_0)
race_1=(race_col[race_col == 1])
print(race_1)
race_2=(race_col[race_col == 2])
print(race_2)
race_3=(race_col[race_col == 3])
print(race_3)
race_4=(race_col[race_col == 4])
print(race_4)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4

In [ ]:
len_0=len(race_0)
print("race0: ",len_0)
len_1=len(race_1)
print("race1: ",len_1)
len_2=len(race_2)
print("race2: ",len_2)
len_3=len(race_3)
print("race3: ",len_3)
len_4=len(race_4)
print("race4: ",len_4)



race0:  10
race1:  27
race2:  110
race3:  6
race4:  847


In [ ]:
min_no_citizen = np.array([len_0,len_1,len_2,len_3,len_4])
a = min_no_citizen.min()
print(a) 
    
if a==len_0:
  print("race0 with the minimum no. of citizens")
elif a==len_1:
  print("race1 with the minimum no. of citizens")
elif a==len_2:
  print("race2 with the minimum no. of citizens")
elif a==len_3:
  print("race2 with the minimum no. of citizens")
elif a==len_4:
  print("race4 with the minimum no. of citizens")
      




6
race2 with the minimum no. of citizens


In [ ]:
minority_race = np.where(min_no_citizen == min(min_no_citizen))

print(minority_race)
print("Index of the race having the least no. of citizens",minority_race[0])

(array([3]),)
Index of the race having the least no. of citizens [3]


In [51]:
senior_citizens = age[age>60]
print(senior_citizens)

[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]


In [58]:
working_hours = data[:,6]

c = np.extract(age>60,working_hours)
working_hours_sum = sum(c)
print(working_hours_sum)

#c= working_hours[np.where(age>60)[0]]
#print(c.size)
#c = working_hours 
#print(c)

1917.0


In [ ]:
senior_citizens_len = len(senior_citizens)
print(senior_citizens_len)

61


In [ ]:
avg_working_hours = working_hours_sum/senior_citizens_len
print(avg_working_hours)   
if avg_working_hours < 25:
  print(" govt. policy is followed.")
else:
  print(" govt. policy not is followed.")

31.42622950819672
 govt. policy not is followed.


In [55]:
education = data[:,1]
high = education[education > 10] 
low = education[education <= 10]
print(high.size)
print(low.size)

327
673


In [ ]:
#high = education[]

In [56]:
income = data[:,7]
pay_high = np.extract(education >10,income)
avg_pay_high = pay_high.mean()
pay_low = np.extract(education <=10,income)
avg_pay_low = pay_low.mean()
print(avg_pay_high)
print(avg_pay_low)


0.42813455657492355
0.13670133729569092
